name: TuyaOpen Check [switch_demo] Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - actions  # 当分支有提交时执行此工作流
jobs:
  Build-Switch-Demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 Running on a ${{ runner.os }}, branch is ${{ github.ref }} !"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          cd ${{ github.workspace }}
          export PATH=$PATH:$(pwd)
          tos version
          tos check
      - run: echo "💡 This job's status is ${{ job.status }}."
